{{- if or .Values.proxytest.enableService .Values.proxytest.enableTraefikIngressRoute }}
apiVersion: v1
kind: Service
metadata:
  name: proxytest
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    app: proxytest
  ports:
  - name: http
    port: 80
    targetPort: 8080
{{- end }}
